# Generated by Django 4.0.4 on 2022-06-12 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('tasks_count', models.IntegerField(default=0, null=True)),
                ('current_task', models.CharField(blank=True, max_length=50, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('company_assigned', models.CharField(blank=True, max_length=50, null=True)),
                ('tasks_count', models.IntegerField(default=0, null=True)),
                ('current_task', models.CharField(blank=True, max_length=50, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_on', models.DateField()),
                ('deadline', models.DateField()),
                ('extensions', models.IntegerField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.account')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeplus.clients')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smeplus.team')),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
