# Generated by Django 4.0.4 on 2022-06-11 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('org_name', models.CharField(max_length=100, null=True)),
                ('org_logo', models.ImageField(blank=True, upload_to='logos')),
                ('subscription_start_date', models.DateField()),
                ('subscription_end_date', models.DateField()),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.CharField(choices=[('survey', 'SURVEY'), ('sme', 'SME'), ('residents', 'RESIDENTS')], max_length=50)),
                ('account_subscription_date', models.DateField(null=True)),
                ('account_expiry_date', models.DateField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
