# Generated by Django 4.0.4 on 2022-06-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_account_account_id_remove_customer_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_expiry_date',
            field=models.DateField(null=True, verbose_name='Account Expiry Date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_subscription_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Account Start Date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Phone No.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='org_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Organisation Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Phone No.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscription_end_date',
            field=models.DateField(verbose_name='Subscription End Date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscription_start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Subscription Start Date'),
        ),
    ]
