# Generated by Django 4.0.4 on 2022-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_account_account_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='root_account',
            field=models.BooleanField(default=False, max_length=50),
        ),
    ]
